server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB