server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

service:
  storage:
    url: http://storage-service:8081
  metadata:
    url: http://metadata-service:8082
