package com.kibikalo.metadataservice.model;

import jakarta.persistence.*;
import lombok.*;
import com.kibikalo.metadataservice.model.FileStatus;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

@Entity
@Table(name = "metadata")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Metadata {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 64)
    private String fileHash;    // unique hash generated by upload service

    @Column(nullable = false)
    private String filePath;

    @Column(nullable = false)
    private String fileFormat;

    private Long fileSize;      // Size in bytes

    @Column(nullable = false)
    private int duration;       // Duration in seconds

    private String codec;

    @Column(nullable = false, updatable = false)
    private OffsetDateTime uploadedAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private FileStatus fileStatus;

    private OffsetDateTime lastModified;

    @PrePersist
    protected void onCreate() {
        uploadedAt = OffsetDateTime.now(ZoneOffset.UTC);
        fileStatus = FileStatus.METADATA_CREATED;
    }

    @PreUpdate
    protected void onUpdate() {
        lastModified = OffsetDateTime.now(ZoneOffset.UTC);
    }

    public FileStatus getFileStatus() {
        return fileStatus;
    }

    public void setFileStatus(FileStatus fileStatus) {
        this.fileStatus = fileStatus;
    }
}