server:
  port: 8085

spring:
  application:
    name: streaming-service

# Eureka client config
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

app:
  minio:
    url: ${MINIO_URL:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    # Bucket where ENCODED files are stored
    bucket:
      processed: ${MINIO_BUCKET_PROCESSED:processed-audio}
    # Duration for pre-signed URLs (e.g., 5 minutes)
    presigned-url-expiry-seconds: ${MINIO_PRESIGNED_EXPIRY:300}
#    external-base-url: ${MINIO_EXTERNAL_URL:http://localhost:9000}
  # Service name used by Feign to find Metadata Service via Eureka
  metadata-service-name: ${METADATA_SERVICE_NAME:metadata-service}

management: # Optional: Actuator endpoints
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: INFO
    com.kibikalo.streamingservice: DEBUG
    io.minio: WARN
    feign.Client: DEBUG
